# Generated by Django 5.1 on 2024-09-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_remove_dvd_media_ptr_remove_livre_media_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeudeplateau',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
