# Generated by Django 5.1 on 2024-09-05 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_jeudeplateau_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeudeplateau',
            name='disponible',
            field=models.BooleanField(default='Oui'),
        ),
        migrations.AlterField(
            model_name='media',
            name='disponible',
            field=models.BooleanField(default='Oui'),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.media')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.member')),
            ],
        ),
    ]
