# Generated by Django 5.1 on 2024-09-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_alter_jeudeplateau_disponible_alter_media_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='numero',
        ),
    ]
